name: "Testing Resources Prohibited Files"

on: 
    push:
    # only trigger on branches, not on tags
        branches: '**'

jobs:
  prohibited-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # checkout full tree
          fetch-depth: 0
      - run: |
          for commit in $(git rev-list ${{ github.base_ref}}..${{ github.sha}}); do
              git checkout $commit
          done
          
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "*(*.txt|*.cmd*)"
        
      - name: Slack Notification
        if: steps.check_files.outputs.files_exists == 'true' 
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: "#FF0000"
          SLACK_MESSAGE: "⛔️PROHIBITED FILES FOUND"

      - name: Throw Fail
        if: steps.check_files.outputs.files_exists == 'true' 
        run: |
            echo "⛔️PROHIBITED FILES FOUND"
            exit 1
