name: "TestRepo Prohibited Files"

on: 
    push:
    # only trigger on branches, not on tags
        branches: '**'

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - name: get file changes
        run: | 
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }}
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "*(*.txt|*.cmd*)"
        
      - name: Slack Notification
        if: steps.check_files.outputs.files_exists == 'true' 
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        
