name: ".txt"

on: 
    push:
    # only trigger on branches, not on tags
        branches: '**'

jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check file existence
        id: check_files
        uses: karilaa-dev/file-existence-action@v3
        with:
          files: "*.txt"
          fail: true

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'false'
        # Only runs if all of the files exists
        run: echo Failed Successfully!
